version: "3.7"

services:
  web:
    build: .
    image: geodjango:0.0.1
    container_name: geodjango
    command: /usr/bin/uvicorn geodjango.asgi:application --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    env_file: .env
    restart: always
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgis/postgis:latest
    container_name: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    env_file: .env
    restart: always

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./static:/static
    depends_on:
      - web

volumes:
  pgdata:
