version: "3.7"

services:
  web:
    build: .
    image: geodjango:0.0.1
    container_name: geodjango
    command: /usr/bin/uvicorn geodjango.asgi:application --host 0.0.0.0 --port 8000
    ports:
      - "8088:8000"
    depends_on:
      db:
        condition: service_healthy
    restart: always

  db:
    image: postgis/postgis:latest
    container_name: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Donsende1
      - POSTGRES_DB=geodjango
    restart: always

volumes:
  pgdata:
